default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432
  username: root
  password: root

development:
  <<: *default
  database: estante-livros_development

test:
  <<: *default
  database: estante-livros_test

production:
  <<: *default
  database: estante-livros_production
  username: estante-livros
  password: <%= ENV['ESTANTE-LIVROS_DATABASE_PASSWORD'] %>
